[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    WiFi
    HTTPClient
    bblanchon/ArduinoJson@^6.21.3
    marian-craciunescu/ESP32Ping@^1.7

build_flags = 
    -D CNC_STATUS_0=0
    -D CNC_STATUS_1=1
    -D CNC_STATUS_2=2
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    ; Memory optimization flags
    -D CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=4
    -D CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=8
    ; HTTP optimization
    -D HTTP_TCP_BUFFER_SIZE=1024

upload_speed = 921600
; Port otomatik tespit edilsin
; upload_port = /dev/ttyUSB0

; Eğer otomatik tespit çalışmazsa, doğru portu belirtin
; (ls -l /dev/ttyUSB* komutunu çalıştırarak bulabilirsiniz)
; Örnek olarak:
; upload_port = /dev/ttyUSB0
; upload_port = /dev/ttyACM0